
name: CI Workflow

on:
  push:
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate HTML File
        run: test -f index.html

      - name: Validate CSS File
        run: test -f style.css

      - name: Build Docker Image
        run: docker build -t devops-portfolio .

      - name: Run Docker Container
        run: |
          docker run -d -p 9090:80 --name portfolio-container devops-portfolio
          sleep 5

      - name: Check Running Container
        run: docker ps

      - name: Save Build Info
        run: echo "CI Pipeline Successful" > build-info.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-info.txt
